project:
  name: "iNaturalist 2021 Mini ResNet-50"
  seed: 42
data:
  train_root: "D:/NK/University_2/Диплом/Датасети/iNaturalist2021/train_mini"
  test_root: "D:/NK/University_2/Диплом/Датасети/iNaturalist2021/val"
  image_size: 224
model:
  pretrained: true
  num_classes: 10000
training:
  epochs: 20
  batch_size: 24
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_workers: 3
  patience: 3
  use_amp: true
paths:
  checkpoint: "../../checkpoints/inaturalist/resnet50_inaturalist_best.pt"
  last_checkpoint: "../../checkpoints/inaturalist/resnet50_inaturalist_last.pt"
  results_dir: "../../results/inaturalist"
