project:
  name: "PBC ResNet-50 Blood Cell Analyzer"
  seed: 42

data:
  root: "D:/NK/University_2/Диплом/Датасети/PBC/PBC_dataset_split/PBC_dataset_split"
  image_size: 224

model:
  pretrained: true
  num_classes: 8

training:
  epochs: 10
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_workers: 0
  patience: 3
  use_amp: true

paths:
  checkpoint: "../../checkpoints/pbc/resnet50_pbc_best.pt"
  last_checkpoint: "../../checkpoints/pbc/resnet50_pbc_last.pt"
  results_dir: "../../results/pbc"
